apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  mongodb-username: {{ .Values.mongodb.username | b64enc }}
  mongodb-password: {{ .Values.mongodb.password | b64enc }}
