apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongodb
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  clusterIP: None
  selector:
    app: mongodb
