replicaCount: 1

image:
  repository: mongo
  tag: "4.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  size: 10Gi
  storageClass: default

mongodb:
  username: "username"
  password: "password"
  databaseName: "mydb"
