replicaCount: 1

image:
  repository: origenai/cloud-engineer-test-sample-app-backend
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

mongodb:
  uri: mongodb://username:password@mongo-svc:27017/mydb
